import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect } from "react";
import svgLoader from 'svg-webgl-loader-opti';
import vertexShader from '../shaders/vertex.glsl';
import fragmentShader from '../shaders/fragment.glsl';

export default function Home() {

  useEffect(() => {
    const canvas = document.getElementById('canvas');
    const gl = canvas.getContext('webgl2', {
      alpha: true,
      depth: false,
      stencil: true,
      antialias: true,
      preserveDrawingBuffer: true,
      powerPreference: 'default',
    });

    (async () => {
      const loader = await svgLoader("/mountain.svg");
      loader.load({
        gl,
        shaders: {
          vertex: vertexShader,
          fragment: fragmentShader,
        },
        loc: {
          width: 400,
          height: 400,
        },
        needTrim: false,
      });

      loader.draw({
        scale: 0.8,
        loc: { x: 0, y: 0 },
        needFill: true,
        needStroke: true,
      });

    })();

  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Your first vector
        </h1>

        <canvas id="canvas" width="400" height="400"></canvas>

      </main>

    </div>
  )
}
